# Generated by Django 5.2 on 2026-06-09 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_documento_propietario_alter_estante_limite_pisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_entidad',
            field=models.CharField(blank=True, choices=[('persona', 'Persona Natural'), ('institucion', 'Institución'), ('empresa', 'Empresa')], default='persona', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_propietario', to='api.persona'),
        ),
    ]
