# Generated by Django 5.2 on 2026-06-10 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_persona_tipo_entidad_alter_documento_propietario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='codigo_doc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='PrestamoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prest', models.DateField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_doc_autorizados', to='api.persona')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_doc_recibidos', to='api.persona')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_doc_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoDocItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devol', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='prestado', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_doc_items', to='api.documento')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.prestamodoc')),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devol', models.DateField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_devolucion', models.CharField(default='buen_estado', max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prestamo_doc_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='api.prestamodocitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProrrogaDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('dias_otorgados', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_solicita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.persona')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prorrogas', to='api.prestamodoc')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
