# Generated by Django 5.2 on 2026-06-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_documento_codigo_doc_prestamodoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bypass_2fa_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
