# Generated by Django 5.2 on 2026-06-11 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_perfil_bypass_2fa_hasta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRESTAMO', 'Préstamo'), ('DEVOLUCION_ESTADO', 'Devolución'), ('VENCIMIENTO', 'Vencimiento'), ('PROXIMO_VENCER', 'Próximo a vencer'), ('BLOQUEO', 'Bloqueo'), ('TRASPASO', 'Traspaso'), ('INCIDENTE', 'Incidente')], max_length=50)),
                ('mensaje', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
