# Generated by Django 5.2 on 2026-06-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha_naci',
        ),
    ]
