# Generated by Django 5.2 on 2026-06-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_fecha_naci_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueo',
            name='motivo_desbloq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
