# Generated by Django 5.2 on 2026-06-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_fecha_limite_prestamo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.devolucion')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documento')),
            ],
        ),
    ]
