# Generated by Django 5.2 on 2026-06-17 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_devoluciondocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': [('gestionar_carpetas', 'Gestionar Carpetas'), ('gestionar_documentos', 'Gestionar Documentos'), ('gestionar_prestamos', 'Gestionar Préstamos'), ('gestionar_devoluciones', 'Gestionar Devoluciones'), ('gestionar_traspasos', 'Gestionar Traspasos'), ('gestionar_ubicaciones', 'Gestionar Ubicaciones'), ('gestionar_personas', 'Gestionar Personas'), ('gestionar_bloqueos', 'Gestionar Bloqueos'), ('gestionar_prorrogas', 'Gestionar Prórrogas'), ('gestionar_retiros', 'Gestionar Retiros'), ('gestionar_usuarios', 'Gestionar Usuarios'), ('ver_dashboard', 'Ver Dashboard y Reportes')]},
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateField()),
                ('motivo', models.CharField(choices=[('traslado', 'Traslado'), ('retiro_indefinido', 'Retiro Indefinido'), ('otro', 'Otro')], max_length=50)),
                ('motivo_otro', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros_autorizados', to='api.persona')),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carpeta')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='api.persona')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
