# Generated by Django 5.2 on 2026-06-18 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_perfil_options_retiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueo',
            name='usuario_desbloqueo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_desbloqueados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloqueo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_realizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
