# Generated by Django 5.2 on 2026-06-19 20:17

import uuid
from django.db import migrations, models


def asignar_token_firma(apps, schema_editor):
    Devolucion = apps.get_model('api', 'Devolucion')
    for d in Devolucion.objects.all():
        d.token_firma = uuid.uuid4()
        d.save(update_fields=['token_firma'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_bloqueo_usuario_desbloqueo_alter_bloqueo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='foto_firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='token_firma',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(asignar_token_firma, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='devolucion',
            name='token_firma',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado_carpeta', 'Prestado (carpeta)'), ('prestado_individual', 'Prestado (individual)')], default='disponible', max_length=20),
        ),
    ]
