# Generated by Django 5.2 on 2026-06-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_devolucion_foto_firma_devolucion_token_firma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueo',
            name='fecha_bloq',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bloqueo',
            name='fecha_desbloq',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_devol',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devoluciondoc',
            name='fecha_devol',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_ingre',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='fecha_reporte',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prest',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prestamocarpeta',
            name='fecha_devol',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamodoc',
            name='fecha_devolucion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prestamodoc',
            name='fecha_prest',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prestamodocitem',
            name='fecha_devol',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prorroga',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prorrogadoc',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha_retiro',
            field=models.DateTimeField(),
        ),
    ]
