# Generated by Django 5.2 on 2026-06-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_bloqueo_fecha_bloq_alter_bloqueo_fecha_desbloq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoluciondoc',
            name='foto_firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='devoluciondoc',
            name='token_firma',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
