# Generated by Django 5.2 on 2026-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_devoluciondoc_foto_firma_devoluciondoc_token_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='foto_firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='token_firma',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
