# Generated by Django 5.2 on 2026-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_normalizar_tipo_incidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamodoc',
            name='foto_firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='prestamodoc',
            name='token_firma',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
