server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redireccionar todas las peticiones a index.html si no se encuentra el archivo físico.
        # Esto es vital para las aplicaciones SPA con React Router.
        try_files $uri $uri/ /index.html;
    }

    # Proxy inverso para reenviar las peticiones de GraphQL al backend de Django
    location /graphql/ {
        proxy_pass http://backend:8000/graphql/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy para subida de fotos y otras APIs REST
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 10M;
    }

    # Redirección en caso de error del servidor
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
